execution:
    uuid: 2c9156f1-9dde-4d24-aebd-d4f162db0dda
    runtime:
        start: 2026-06-06T10:51:51.116229-07:00
        end: 2026-06-06T10:54:37.813455-07:00
        duration: 2 minutes, 46 seconds, and 697226 microseconds
    execution_context:
        type: synchronous

action:
    type: method
    plugin: !ref 'environment:plugins:cutadapt'
    action: trim_paired
    inputs:
    -   demultiplexed_sequences: 49b0465b-449f-49ca-9fd7-f8dca011568a
    parameters:
    -   adapter_f: null
    -   front_f:
        - NTGYCAGCMGCCGCGGTAA
    -   anywhere_f: null
    -   adapter_r: null
    -   front_r:
        - NCGYCAATTYMTTTRAGTTT
    -   anywhere_r: null
    -   forward_cut: 0
    -   reverse_cut: 0
    -   error_rate: 0.1
    -   indels: true
    -   times: 1
    -   overlap: 3
    -   match_read_wildcards: false
    -   match_adapter_wildcards: true
    -   minimum_length: 1
    -   discard_untrimmed: true
    -   max_expected_errors: null
    -   max_n: null
    -   quality_cutoff_5end: 0
    -   quality_cutoff_3end: 0
    -   quality_base: 33
    -   cores: 10
    -   nextseq_trim: 0
    output-name: trimmed_sequences

transformers:
    inputs:
        demultiplexed_sequences:
        -   from: SingleLanePerSamplePairedEndFastqDirFmt
            to: SingleLanePerSamplePairedEndFastqDirFmt
    output:
    -   from: CasavaOneEightSingleLanePerSampleDirFmt
        to: SingleLanePerSamplePairedEndFastqDirFmt
        plugin: !ref 'environment:plugins:types'

environment:
    platform: macOS-26.5-x86_64-i386-64bit
    python: |-
        3.12.13 | packaged by conda-forge | (main, Mar  5 2026, 16:51:19) [Clang 19.1.7 ]
    framework:
        version: 2026.4.0
        website: https://qiime2.org
        citations:
        - !cite 'framework|rachis:2026.4.0|0'
    plugins:
        types:
            version: 2026.4.0
            website: https://github.com/qiime2/q2-types
        cutadapt:
            version: 2026.4.0
            website: https://github.com/qiime2/q2-cutadapt
            citations:
            - !cite 'plugin|cutadapt:2026.4.0|0'
    python-packages:
        altair: 6.0.0
        annotated-doc: 0.0.4
        annotated-types: 0.7.0
        anyio: 4.13.0
        appdirs: 1.4.4
        appnope: 0.1.4
        array-api-compat: 1.14.0
        astor: 0.8.1
        asttokens: 3.0.1
        atpublic: 7.0.0
        attrs: 26.1.0
        autocommand: 2.2.2
        backports.tarfile: 1.2.0
        backports.zstd: 1.3.0
        base58: 2.1.1
        bibtexparser: 1.4.4
        biom_format: 2.1.17
        blinker: 1.9.0
        boto3: 1.43.11
        botocore: 1.43.11
        Brotli: 1.2.0
        brotlicffi: 1.2.0.1
        cached-property: 1.5.2
        cachetools: 7.1.3
        certifi: 2026.5.20
        cffi: 2.0.0
        chardet: 5.2.0
        charset-normalizer: 3.4.7
        click: 8.1.8
        colorama: 0.4.6
        comm: 0.2.3
        conda-pack: 0.0.0
        contourpy: 1.3.3
        cutadapt: '5.2'
        cycler: 0.12.1
        deblur: 1.1.1
        debugpy: 1.8.20
        decorator: 5.2.1
        DendroPy: 5.0.8
        dill: 0.4.1
        dnaio: 1.2.2
        dnspython: 2.8.0
        emperor: 1.0.5
        entrezpy: 2.1.3
        exceptiongroup: 1.3.1
        executing: 2.2.1
        fastcluster: 1.3.0
        feedparser: 6.0.12
        filelock: 3.28.0
        flufl.lock: 9.0.0
        fonttools: 4.62.0
        formulaic: 1.2.1
        frictionless: 5.5.0
        future: 1.0.0
        gitdb: 4.0.12
        GitPython: 3.1.50
        h11: 0.16.0
        h2: 4.3.0
        h5py: 3.15.1
        hdmedians: 0.14.2
        hpack: 4.1.0
        httpcore: 1.0.9
        httptools: 0.7.1
        httpx: 0.28.1
        humanize: 4.15.0
        hyperframe: 6.1.0
        idna: '3.11'
        ijson: 3.5.0
        importlib_metadata: 8.7.1
        inflate64: 1.0.4
        iniconfig: 2.3.0
        interface_meta: 1.3.0
        iow: 1.0.8
        ipykernel: 7.2.0
        ipython: 9.12.0
        ipython_pygments_lexers: 1.1.1
        ipywidgets: 8.1.8
        isal: 0.0.0
        isodate: 0.7.2
        itsdangerous: 2.2.0
        jaraco.context: 6.1.0
        jaraco.functools: 4.4.0
        jaraco.text: 4.0.0
        jedi: 0.19.2
        Jinja2: 3.1.6
        jmespath: 1.1.0
        joblib: 1.5.3
        jsonschema: 4.26.0
        jsonschema-specifications: 2025.9.1
        jupyter_client: 8.8.0
        jupyter_core: 5.9.1
        jupyterlab_widgets: 3.0.16
        kiwisolver: 1.5.0
        llvmlite: 0.47.0
        lxml: 6.0.4
        lz4: 4.4.5
        markdown-it-py: 4.0.0
        marko: 2.2.2
        MarkupSafe: 3.0.3
        matplotlib: 3.10.8
        matplotlib-inline: 0.2.1
        mdurl: 0.1.2
        mizani: 0.14.4
        more-itertools: 10.8.0
        multivolumefile: 0.2.3
        munkres: 1.1.4
        mypy_extensions: 1.1.0
        narwhals: 2.19.0
        natsort: 8.4.0
        ncbi-datasets-pyclient: 18.18.0
        nest_asyncio: 1.6.0
        networkx: 3.6.1
        nlopt: 2.10.1
        numba: 0.65.0
        numpy: 2.4.2
        packaging: '26.0'
        pandas: 2.3.3
        pandera: 0.30.1
        parsl: 2026.2.23
        parso: 0.8.6
        PASTA: 1.9.3
        patsy: 1.0.2
        petl: 1.7.17
        pexpect: 4.9.0
        pillow: 12.1.1
        pip: 26.0.1
        platformdirs: 4.4.0
        plotnine: 0.15.4
        pluggy: 1.6.0
        prompt_toolkit: 3.0.52
        protobuf: 6.33.5
        psutil: 7.2.2
        ptyprocess: 0.7.0
        pure_eval: 0.2.3
        py7zr: 1.0.0
        pyarrow: 24.0.0
        pybcj: 1.0.7
        pycparser: '2.22'
        pycryptodomex: 3.23.0
        pydantic: 2.13.1
        pydantic_core: 2.46.1
        pydeck: 0.9.2
        Pygments: 2.20.0
        pyhmmer: 0.12.0
        pymongo: 4.16.0
        Pympler: '1.1'
        pynndescent: 0.5.13
        pyparsing: 3.3.2
        pyppmd: 1.1.0
        PySocks: 1.7.1
        pytest: 9.0.3
        python-dateutil: 2.9.0.post0
        python-dotenv: 1.2.2
        python-multipart: 0.0.29
        python-slugify: 8.0.4
        pytz: 2026.1.post1
        PyYAML: 6.0.3
        pyzmq: 27.1.0
        pyzotero: 1.11.0
        pyzstd: 0.19.1
        q2-alignment: 2026.4.0
        q2-boots: 2026.4.0
        q2-composition: 2026.4.0
        q2-cutadapt: 2026.4.0
        q2-dada2: 2026.4.0
        q2-deblur: 2026.4.0
        q2-demux: 2026.4.0
        q2-diversity: 2026.4.0
        q2-diversity-lib: 2026.4.0
        q2-emperor: 2026.4.0
        q2-feature-classifier: 2026.4.0
        q2-feature-table: 2026.4.0
        q2-fondue: 2026.4.0
        q2-fragment-insertion: 2026.4.0
        q2-kmerizer: 2026.4.0
        q2-longitudinal: 2026.4.0
        q2-metadata: 2026.4.0
        q2-mystery-stew: 2026.4.0
        q2-phylogeny: 2026.4.0
        q2-quality-control: 2026.4.0
        q2-quality-filter: 2026.4.0
        q2-sample-classifier: 2026.4.0
        q2-stats: 2026.4.0
        q2-taxa: 2026.4.0
        q2-types: 2026.4.0
        q2-vizard: 2026.4.0
        q2-vsearch: 2026.4.0
        q2cli: 2026.4.0
        q2templates: 2026.4.0
        qiime2: 2026.4.0
        rachis: 2026.4.0
        referencing: 0.37.0
        requests: 2.33.1
        rescript: 2026.4.0
        rfc3986: 2.0.0
        rich: 15.0.0
        rnanorm: 2.1.0
        rpds-py: 0.30.0
        rpy2: 3.6.4
        rpy2-rinterface: 3.6.3
        rpy2-robjects: 3.6.3
        s3transfer: 0.17.0
        scikit-bio: 0.7.2
        scikit-learn: 1.7.1
        scipy: 1.17.1
        seaborn: 0.13.2
        semver: 3.0.4
        sepp: 4.5.6
        setproctitle: 1.3.7
        setuptools: 82.0.1
        sgmllib3k: 1.0.0
        shellingham: 1.5.4
        simpleeval: 1.0.7
        six: 1.17.0
        smmap: 5.0.3
        sniffio: 1.3.1
        sortedcontainers: 2.4.0
        stack_data: 0.6.3
        starlette: 1.0.0
        statsmodels: 0.14.6
        streamlit: 1.57.0
        stringcase: 1.2.0
        tabulate: 0.10.0
        tblib: 3.2.2
        tenacity: 9.1.4
        text-unidecode: '1.3'
        texttable: 1.7.0
        threadpoolctl: 3.6.0
        toml: 0.10.2
        tomli: 2.4.0
        tomlkit: 0.14.0
        tornado: 6.5.5
        tqdm: 4.67.3
        traitlets: 5.14.3
        typeguard: 4.5.1
        typer: 0.23.1
        typing-inspection: 0.4.2
        typing_extensions: 4.15.0
        typing_inspect: 0.9.0
        tzdata: '2026.1'
        tzlocal: 5.3.1
        umap-learn: 0.5.11
        unicodedata2: 17.0.1
        unifrac: '1.5'
        urllib3: 2.6.3
        uvicorn: 0.47.0
        validators: 0.35.0
        watchdog: 6.0.0
        wcwidth: 0.6.0
        websockets: '16.0'
        wheel: 0.46.3
        whenever: 0.10.0
        widgetsnbextension: 4.0.15
        wrapt: 2.1.2
        xmltodict: 1.0.4
        xopen: 2.0.2
        zipfile-deflate64: 0.0.0
        zipp: 3.23.0
        zlib-ng: 0.0.0
        zstandard: 0.25.0
